Repository SUSE/ha-sap-terraform-deployments, pull requests merged in 2020-04, with the labels that each got.

#410 Create iscsi server module for AWS provider
  aws/README.md
  aws/instances.tf
  aws/main.tf
  aws/modules/iscsi_server/main.tf
  aws/modules/iscsi_server/outputs.tf
  aws/modules/iscsi_server/salt_provisioner.tf
  aws/modules/iscsi_server/variables.tf
  aws/outputs.tf
  aws/salt_provisioner.tf
  aws/terraform.tfvars.example
  aws/variables.tf
Labels: stale

#383 Feature/gcp resources
  gcp/README.md
  gcp/modules/drbd_node/salt_provisioner.tf
  gcp/modules/netweaver_node/salt_provisioner.tf
  gcp/salt_provisioner.tf
  pillar_examples/automatic/drbd/cluster.sls
  pillar_examples/automatic/hana/cluster.sls
  pillar_examples/automatic/netweaver/cluster.sls
  salt/drbd_node/files/templates/drbd_cluster.j2
Labels: Not merge

#439 Remove hardcoded storage devices on GCE
  gcp/main.tf
  gcp/modules/drbd_node/salt_provisioner.tf
  gcp/modules/hana_node/salt_provisioner.tf
  gcp/modules/iscsi_server/salt_provisioner.tf
  gcp/modules/netweaver_node/salt_provisioner.tf
  gcp/terraform.tfvars.example
  gcp/variables.tf
  pillar_examples/automatic/drbd/drbd.sls
  salt/hana_node/download_hana_inst.sls
  salt/netweaver_node/installation_files.sls
Labels: gcp
